### PR TITLE
Adl2 ++

### PR DESCRIPTION
**Pull request by joostholslag**
draft PR to allow commenting and suggestions.

### CODE REVIEW

**Comment by freshehr** [comment]
@joostholslag - Suggest pausing any comments briefly as @sebastian-iancu and I have been working to update the asciidoc to support tabs, plus have made some small changes to the preface / ADL2.4 Changes part of the document. Should bereay to view very soon.

**Comment by joostholslag** [comment]
> @joostholslag - Suggest pausing any comments briefly as @sebastian-iancu and I have been working to update the asciidoc to support tabs, plus have made some small changes to the preface / ADL2.4 Changes part of the document. Should bereay to view very soon.

Thanks a lot for the timely warning! As discussed over the phone, I'll take my chances of having to re do. Because I really want to record my comments right now.

**Comment by sebastian-iancu** [comment]
closed this PR for now to avoid confusion over what will be merged to master

**Comment by joostholslag** [comment]
All comments on this PR have either been resolved or copied into https://github.com/openEHR/specifications-AM/pull/16/files
So, proabably after merging that PR, we could delete this branch.

**Pull request closed without merging**
